### ISSUE TITLE
Crashloopbackoff while deploying nifi-with-ldap-authentication-with-toolkit

### ISSUE THREAD

**Issue by Smeks1** [sushilkm/nifi-chart#2]
I am having issues deploying "deploy-secured-nifi-with-ldap-authentication-with-toolkit" on my k8s cluster and hoping you can help me identify what the problem is.

After deploying I have 3/4 nifi-0 pod ready and status is crashloopbackoff screenshot attached.

My K8s setup is on GCP with the below resources 
Cluster size -4 Total cores -8 Total memory -32.00 GB

Changes I made to value.yml file are:
replica count =1
persistence:
  storageClass: standard
  accessModes:  [ReadWriteOnce]
  configPartitionSize: 5Mi
  dataPartition1Size: 10Gi
  dataPartition2Size: 10Gi
  dataPartition3Size: 10Gi
  logPartitionSize: 5Gi
# Configure resource requests for nifi pods
resources:
  requests:
    memory: "4Gi"
    cpu: "0.5"
 
I also added my ldap url and credentials to ldap-value.yml file 

Please let me know what other info or details you might require. I had attached "kubectl describe po nifi-0",  nifi-0 server logs
and app-logs.

![image](https://user-images.githubusercontent.com/32819112/102018210-80b86180-3d74-11eb-95e0-832e4adbdb61.png)
![image](https://user-images.githubusercontent.com/32819112/102018441-ebb66800-3d75-11eb-9422-ecfdbc34a04b.png)
[server-log.txt](https://github.com/sushilkm/nifi-chart/files/5685011/server-log.txt)
[app-log.txt](https://github.com/sushilkm/nifi-chart/files/5685032/app-log.txt)
[describe.txt](https://github.com/sushilkm/nifi-chart/files/5685033/describe.txt)

**Comment by sushilkm** [comment]
Thank you @Smeks1 for trying the chart.
I found the following error message in the app-log.txt
```Error creating bean with name 'authorizer': FactoryBean threw exception on object creation; nested exception is org.springframework.ldap.CommunicationException: ldaps.bwt.ee:636; nested exception is javax.naming.CommunicationException: ldaps.bwt.ee:636 [Root exception is java.net.SocketTimeoutException: connect timed out]```

It looks like it is not able to reach the ldap server at `ldaps.bwt.ee:636`

**Comment by Smeks1** [comment]
@sushilkm Hi, 
Yes you are correct, the ldap server is not reachable. I'll need to whitelist the nodes IP but could this be the reason for crashloopbackoff? I wasn't expecting this to be the reason.

**Comment by sushilkm** [comment]
For now, I can only see that as the error message in the logs provided.

**Comment by Smeks1** [comment]
Okay, I’ll let you know the outcome once I have the IP whitelisted.

**Comment by Smeks1** [comment]
Hello,
I whitelisted my nodes ip but this didn't resolve the issue. I was still getting the above error. I deployed another container from my cluster just for the purpose of troubleshooting and from that container, I was able to telnet to the LDAP server. I have double checked my credentials (managerdn, managerpassword and url) and all seem correct. Do you have any other troubleshooting suggestions for me?

**Comment by sushilkm** [comment]
will it be ok, if I asked you what is the ldap url you are using.

**Comment by Smeks1** [comment]
Can I somehow share it with you privately? email/skype/whatsapp? my email address is nwaokobia.osemeke@gmail.com, whatsapp: +37253529124 or any other means best preferred by you

**Comment by sushilkm** [comment]
sure you can send me emails at skm.net@gmail.com

**Comment by sushilkm** [comment]
as discussed on email, it is working now. closing the issue.
You can reopen if you still have any problems or questions.
Thank you for trying the chart.
